---
abstract: 'generate secure random pronounceable passwords'
author:
  - 'Jörg Walter <jwalt@cpan.org>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-GeneratePassword
requires:
  Data::Dumper: '0'
  Exporter: '0'
  perl: '5.006'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/Crypt-GeneratePassword
  repository: https://github.com/neilbowers/Crypt-GeneratePassword.git
version: '0.04'
